REGISTRY_PORT_NUMBER = 6000
REGISTRY_PUSH_PORT_NUMBER = 40000
REGISTRY_PUB_PORT_NUMBER = 40001
BROKER_PORT_NUMBER = 6001
PUBLISHER_PORT_NUMBER = 5555
SUBSCRIBER_PORT_NUMBER = 5556

REGISTRY = "registry"
REGISTER = "register"
DISCOVER = "discover"

PUB = "pub"
SUB = "sub"
BROKER = "broker"
DIRECT = "direct"
BROKER_IP = "brokerIP"
BROKER_PORT = "brokerPort"
REGISTRY_NODES = "registryNodes"
