REGISTRY_PORT_NUMBER = 6000
REGISTRY_PUSH_PORT_NUMBER = 40000
REGISTRY_PUB_PORT_NUMBER = 40001
BROKER_PORT_NUMBER = 6001
PUBLISHER_PORT_NUMBER = 5555
SUBSCRIBER_PORT_NUMBER = 5556
CACHE_PORT_NUMBER = 6002

REGISTRY = "registry"
REGISTER = "register"
DISCOVER = "discover"
HISTORY = "history"

PUB = "pub"
SUB = "sub"
BROKER = "broker"
DIRECT = "direct"
BROKER_IP = "brokerIP"
BROKER_PORT = "brokerPort"
REGISTRY_NODES = "registryNodes"
BROKER_NODES = "brokerNodes"

PUB_COUNT = "pubCount"
SUB_COUNT = "subCount"
BROKER_COUNT = "brokerCount"

KAZOO_IP = "10.0.0.1"
KAZOO_PORT = "2181"

KAZOO_BROKER_PATH = "/broker"
KAZOO_BROKERS_PATH = "/brokers"
KAZOO_REGISTRY_PATH = "/registry"
KAZOO_REGISTRIES_PATH = "/registries"

REPLICA = "replica"
